# Generated by Django 6.1 on 2026-08-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scenes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='scene_data',
            field=models.JSONField(default=dict),
        ),
    ]
