# Generated by Django 6.1 on 2026-09-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0002_scene_scene_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
