# Generated by Django 6.1 on 2026-09-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scenes', '0003_scene_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='status',
            field=models.CharField(
                choices=[
                    ('processing', 'Processing'),
                    ('completed', 'Completed'),
                    ('failed', 'Failed'),
                ],
                default='processing',
                max_length=20,
            ),
        ),
    ]
